version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "13306:3306"
    volumes:
      - ./.docker/mysql/setting:/etc/mysql/conf.d
      - ./.docker/mysql/initialize:/docker-entrypoint-initdb.d